// Code generated by scripts/topic_taxonomy/generate_topic_taxonomy.py; DO NOT EDIT.

package main

import "strings"

// Natural resources decision: Retain the existing `naturalresources` topic as canonical. Its stable ID is already stored in iOS user preferences and used by natural-resource context features, so the backend must adopt that same ID and keyword set instead of dropping it.
var topicKeywordsByID = map[string][]string{
	"housing":          []string{"housing", "rent", "mortgage", "affordable housing", "logement", "loyer"},
	"healthcare":       []string{"health", "pharmacare", "mental health", "dental", "pandemic", "santé"},
	"climate":          []string{"climate", "carbon", "environment", "clean energy", "net zero", "emission", "énergie", "environnement"},
	"economy":          []string{"budget", "fiscal", "inflation", "economic", "gdp", "debt", "déficit", "économie"},
	"indigenous":       []string{"indigenous", "first nations", "métis", "inuit", "reconciliation", "autochtone"},
	"immigration":      []string{"immigration", "refugee", "asylum", "citizenship", "border", "réfugié"},
	"defence":          []string{"defence", "military", "NATO", "armed forces", "veteran", "Veterans Affairs", "ancien combattant", "défense", "armée"},
	"justice":          []string{"justice", "crime", "police", "firearms", "gun", "corrections", "correctional", "prison", "parole", "recidivism", "incarceration", "sécurité"},
	"seniors":          []string{"senior", "pension", "retirement", "old age", "aîné", "retraite"},
	"agriculture":      []string{"agriculture", "farming", "food security", "grain", "livestock"},
	"transport":        []string{"transport", "rail", "aviation", "highway", "infrastructure", "transit"},
	"taxation":         []string{"tax", "GST", "HST", "income tax", "corporate tax", "impôt", "taxe"},
	"foreign":          []string{"foreign affairs", "international", "Ukraine", "Gaza", "sanctions", "treaty", "affaires étrangères"},
	"education":        []string{"education", "student", "student debt", "youth", "university", "school", "tuition", "éducation", "étudiant"},
	"childcare":        []string{"child care", "daycare", "family", "children", "services de garde", "enfant"},
	"energy":           []string{"energy", "oil", "gas", "pipeline", "electricity", "LNG", "pétrole"},
	"naturalresources": []string{"natural resources", "forestry", "forest", "lumber", "timber", "mining", "minerals", "mineral production", "potash", "wood harvest", "ressources naturelles", "foresterie", "mines"},
	"pharma":           []string{"drug", "pharmaceutical", "medication", "opioid", "naloxone", "médicament"},
	"digital":          []string{"digital", "artificial intelligence", "AI", "online harms", "privacy", "cybersecurity", "numérique"},
	"labour":           []string{"labour", "labor", "union", "strike", "wage", "employment", "travail", "grève"},
	"trade":            []string{"trade", "tariff", "CUSMA", "CETA", "export", "import", "commerce", "tarif"},
}

func followedTopicKeywords(ids []string) []string {
	if len(ids) == 0 {
		return nil
	}

	seen := make(map[string]struct{})
	keywords := make([]string, 0)
	for _, id := range ids {
		for _, keyword := range topicKeywordsByID[id] {
			normalized := strings.ToLower(strings.TrimSpace(keyword))
			if normalized == "" {
				continue
			}
			if _, exists := seen[normalized]; exists {
				continue
			}
			seen[normalized] = struct{}{}
			keywords = append(keywords, normalized)
		}
	}
	return keywords
}
