#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "shared/topic-taxonomy/parliamentary_topics.json"
SWIFT_OUT = ROOT / "ios/epac/Model/ParliamentaryTopic.swift"
TOPIC_NOTIFIER_OUT = ROOT / "backend/topic-notifier/topic_taxonomy_gen.go"
SEARCH_OUT = ROOT / "backend/search/internal/usecase/topic_taxonomy_gen.go"
CATALOG_OUT = ROOT / "docs/architecture/use-case-catalog.md"


def load_taxonomy() -> dict:
    payload = json.loads(SOURCE.read_text())
    topics = payload.get("topics", [])
    if not topics:
        raise SystemExit(f"{SOURCE} has no topics")

    ids = set()
    name_keys = set()
    for topic in topics:
        topic_id = topic["id"]
        if topic_id in ids:
            raise SystemExit(f"duplicate topic id: {topic_id}")
        ids.add(topic_id)
        name_key = topic["name_key"]
        if name_key in name_keys:
            raise SystemExit(f"duplicate name_key: {name_key}")
        name_keys.add(name_key)
        keywords = topic["keywords"]
        if not keywords:
            raise SystemExit(f"topic {topic_id} has no keywords")
        if len({kw.lower() for kw in keywords}) != len(keywords):
            raise SystemExit(f"topic {topic_id} contains duplicate keywords ignoring case")

    if "naturalresources" not in ids:
        raise SystemExit("canonical taxonomy must retain naturalresources")
    if "naturalresources_decision" not in payload.get("metadata", {}):
        raise SystemExit("canonical taxonomy metadata must document the naturalresources decision")
    return payload


def swift_string(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def go_string(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def render_swift(payload: dict) -> str:
    topics = payload["topics"]
    lines = [
        "//",
        "//  ParliamentaryTopic.swift",
        "//  epac",
        "//",
        "//  Generated by scripts/topic_taxonomy/generate_topic_taxonomy.py",
        "//  from shared/topic-taxonomy/parliamentary_topics.json.",
        "//  Do not edit this file by hand.",
        "//",
        "",
        "import Foundation",
        "",
        "struct ParliamentaryTopic: Identifiable, Codable, Hashable {",
        "    let id: String          // stable lowercase slug, e.g. \"housing\"",
        "    let nameKey: String     // localization key, e.g. \"topic.housing\"",
        "    let keywords: [String]  // case-insensitive substrings to match in titles",
        "",
        "    var localizedName: String { NSLocalizedString(nameKey, comment: \"\") }",
        "",
        "    static let all: [ParliamentaryTopic] = [",
    ]
    for topic in topics:
        keywords = ", ".join(f'\"{swift_string(keyword)}\"' for keyword in topic["keywords"])
        lines.append(
            f'        ParliamentaryTopic(id: \"{swift_string(topic["id"])}\", '
            f'nameKey: \"{swift_string(topic["name_key"])}\", '
            f'keywords: [{keywords}]),'
        )
    lines[-1] = lines[-1].rstrip(",")
    lines.extend(
        [
            "    ]",
            "",
            "    /// Returns all topics whose keywords match the given text.",
            "    static func matching(_ text: String) -> [ParliamentaryTopic] {",
            "        let lower = text.lowercased()",
            "        return all.filter { topic in",
            "            topic.keywords.contains { lower.contains($0.lowercased()) }",
            "        }",
            "    }",
            "}",
        ]
    )
    return "\n".join(lines) + "\n"


def render_topic_notifier_go(payload: dict) -> str:
    topics = payload["topics"]
    note = payload["metadata"]["naturalresources_decision"]
    lines = [
        "// Code generated by scripts/topic_taxonomy/generate_topic_taxonomy.py; DO NOT EDIT.",
        "",
        "package main",
        "",
        'import "strings"',
        "",
        "// topic is canonical parliamentary topic policy shared with iOS.",
        "type topic struct {",
        "\tid       string",
        "\tname     string",
        "\tkeywords []string",
        "}",
        "",
        f"// Natural resources decision: {note}",
        "var topics = []topic{",
    ]
    for topic in topics:
        keywords = ", ".join(f'\"{go_string(keyword)}\"' for keyword in topic["keywords"])
        lines.append(
            f'\t{{id: \"{go_string(topic["id"])}\", name: \"{go_string(topic["backend_name"])}\", keywords: []string{{{keywords}}}}},'
        )
    lines.extend(
        [
            "}",
            "",
            "// matchTopics returns IDs of topics whose keywords appear in the subject title.",
            "func matchTopics(subjectTitle string) []string {",
            "\tlower := strings.ToLower(subjectTitle)",
            "\tvar matched []string",
            "\tfor _, t := range topics {",
            "\t\tfor _, kw := range t.keywords {",
            "\t\t\tif strings.Contains(lower, strings.ToLower(kw)) {",
            "\t\t\t\tmatched = append(matched, t.id)",
            "\t\t\t\tbreak",
            "\t\t\t}",
            "\t\t}",
            "\t}",
            "\treturn matched",
            "}",
            "",
            "func topicName(id string) string {",
            "\tfor _, t := range topics {",
            "\t\tif t.id == id {",
            "\t\t\treturn t.name",
            "\t\t}",
            "\t}",
            "\treturn id",
            "}",
        ]
    )
    return "\n".join(lines) + "\n"


def render_search_go(payload: dict) -> str:
    topics = payload["topics"]
    note = payload["metadata"]["naturalresources_decision"]
    lines = [
        "// Code generated by scripts/topic_taxonomy/generate_topic_taxonomy.py; DO NOT EDIT.",
        "",
        "package usecase",
        "",
        'import "strings"',
        "",
        f"// Natural resources decision: {note}",
        "var topicKeywordsByID = map[string][]string{",
    ]
    for topic in topics:
        keywords = ", ".join(f'\"{go_string(keyword)}\"' for keyword in topic["keywords"])
        lines.append(f'\t\"{go_string(topic["id"])}\": []string{{{keywords}}},')
    lines.extend(
        [
            "}",
            "",
            "func FollowedTopicKeywords(ids []string) []string {",
            "\tif len(ids) == 0 {",
            "\t\treturn nil",
            "\t}",
            "",
            "\tseen := make(map[string]struct{})",
            "\tkeywords := make([]string, 0)",
            "\tfor _, id := range ids {",
            "\t\tfor _, keyword := range topicKeywordsByID[id] {",
            "\t\t\tnormalized := strings.ToLower(strings.TrimSpace(keyword))",
            "\t\t\tif normalized == \"\" {",
            "\t\t\t\tcontinue",
            "\t\t\t}",
            "\t\t\tif _, exists := seen[normalized]; exists {",
            "\t\t\t\tcontinue",
            "\t\t\t}",
            "\t\t\tseen[normalized] = struct{}{}",
            "\t\t\tkeywords = append(keywords, normalized)",
            "\t\t}",
            "\t}",
            "\treturn keywords",
            "}",
        ]
    ) 
    return "\n".join(lines) + "\n"


def gofmt(content: str) -> str:
    result = subprocess.run(
        ["gofmt"],
        input=content,
        text=True,
        capture_output=True,
        check=True,
    )
    return result.stdout


def render_catalog(payload: dict) -> str:
    note = payload["metadata"]["naturalresources_decision"]
    return f"""# epac Use-Case Catalog

> Initial catalog slice generated as part of EPAC-1766. Expand as additional use cases are extracted.

## FollowTopic

- **Intent:** Persist followed parliamentary topic IDs and notification granularity without changing existing stored preference semantics.
- **Inputs:** Topic ID, follow/unfollow intent, optional notification granularity.
- **Outputs:** Updated local follow state, backend device registration payload with stable `topic_ids` and `granularity` keys.
- **Domain contract:** Topic IDs come from `shared/topic-taxonomy/parliamentary_topics.json`.

## MatchParliamentaryTopics

- **Intent:** Match Hansard subject titles and related text against the canonical parliamentary topic taxonomy.
- **Inputs:** Free-form debate or speech title text.
- **Outputs:** Zero or more canonical topic IDs in taxonomy order.
- **Policy notes:** Keywords are product policy, shared across iOS and backend adapters. {note}

## NotifyTopicFollowers

- **Intent:** Notify subscribed users when a matched parliamentary topic is debated.
- **Inputs:** Sitting date, debate subject title, canonical topic IDs, subscriber preferences.
- **Outputs:** Backward-compatible APNs payloads with `topic_id` and `hansard_date` keys unchanged.
- **Dependency:** Uses `MatchParliamentaryTopics` and the canonical taxonomy rather than an adapter-local copy.
"""


def write_or_check(path: Path, expected: str, check: bool) -> bool:
    current = path.read_text() if path.exists() else None
    if check:
        return current == expected
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(expected)
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated files are out of date")
    args = parser.parse_args()

    payload = load_taxonomy()
    outputs = {
        SWIFT_OUT: render_swift(payload),
        TOPIC_NOTIFIER_OUT: gofmt(render_topic_notifier_go(payload)),
        SEARCH_OUT: gofmt(render_search_go(payload)),
        CATALOG_OUT: render_catalog(payload),
    }

    stale = []
    for path, content in outputs.items():
        ok = write_or_check(path, content, check=args.check)
        if not ok:
            stale.append(path)

    if args.check and stale:
        for path in stale:
            print(f"out of date: {path.relative_to(ROOT)}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
