#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "shared/topic-taxonomy/parliamentary_topics.json"
SWIFT_OUT = ROOT / "ios/epac/Model/ParliamentaryTopic.swift"


def load_taxonomy() -> dict:
    payload = json.loads(SOURCE.read_text())
    topics = payload.get("topics", [])
    if not topics:
        raise SystemExit(f"{SOURCE} has no topics")

    ids = set()
    name_keys = set()
    for topic in topics:
        topic_id = topic["id"]
        if topic_id in ids:
            raise SystemExit(f"duplicate topic id: {topic_id}")
        ids.add(topic_id)
        name_key = topic["name_key"]
        if name_key in name_keys:
            raise SystemExit(f"duplicate name_key: {name_key}")
        name_keys.add(name_key)
        keywords = topic["keywords"]
        if not keywords:
            raise SystemExit(f"topic {topic_id} has no keywords")
        if len({kw.lower() for kw in keywords}) != len(keywords):
            raise SystemExit(f"topic {topic_id} contains duplicate keywords ignoring case")

    if "naturalresources" not in ids:
        raise SystemExit("canonical taxonomy must retain naturalresources")
    if "naturalresources_decision" not in payload.get("metadata", {}):
        raise SystemExit("canonical taxonomy metadata must document the naturalresources decision")
    return payload


def swift_string(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def render_swift(payload: dict) -> str:
    topics = payload["topics"]
    lines = [
        "//",
        "//  ParliamentaryTopic.swift",
        "//  epac",
        "//",
        "//  Generated by scripts/topic_taxonomy/generate_topic_taxonomy.py",
        "//  from shared/topic-taxonomy/parliamentary_topics.json.",
        "//  Do not edit this file by hand.",
        "//",
        "",
        "import Foundation",
        "",
        "struct ParliamentaryTopic: Identifiable, Codable, Hashable, Sendable {",
        "    let id: String          // stable lowercase slug, e.g. \"housing\"",
        "    let nameKey: String     // localization key, e.g. \"topic.housing\"",
        "    let keywords: [String]  // case-insensitive substrings to match in titles",
        "",
        "    var localizedName: String { NSLocalizedString(nameKey, comment: \"\") }",
        "",
        "    static let all: [ParliamentaryTopic] = [",
    ]
    for topic in topics:
        keywords = ", ".join(f'\"{swift_string(keyword)}\"' for keyword in topic["keywords"])
        lines.append(
            f'        ParliamentaryTopic(id: \"{swift_string(topic["id"])}\", '
            f'nameKey: \"{swift_string(topic["name_key"])}\", '
            f'keywords: [{keywords}]),'
        )
    lines[-1] = lines[-1].rstrip(",")
    lines.extend(
        [
            "    ]",
            "",
            "    /// Returns all topics whose keywords match the given text.",
            "    static func matching(_ text: String) -> [ParliamentaryTopic] {",
            "        let lower = text.lowercased()",
            "        return all.filter { topic in",
            "            topic.keywords.contains { lower.contains($0.lowercased()) }",
            "        }",
            "    }",
            "}",
        ]
    )
    return "\n".join(lines) + "\n"


def write_or_check(path: Path, expected: str, check: bool) -> bool:
    current = path.read_text() if path.exists() else None
    if check:
        return current == expected
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(expected)
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated files are out of date")
    args = parser.parse_args()

    payload = load_taxonomy()
    outputs = {
        SWIFT_OUT: render_swift(payload),
    }

    stale = []
    for path, content in outputs.items():
        ok = write_or_check(path, content, check=args.check)
        if not ok:
            stale.append(path)

    if args.check and stale:
        for path in stale:
            print(f"out of date: {path.relative_to(ROOT)}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
