// Code generated by scripts/topic_taxonomy/generate_topic_taxonomy.py; DO NOT EDIT.

package main

import "strings"

// topic is canonical parliamentary topic policy shared with iOS.
type topic struct {
	id       string
	name     string
	keywords []string
}

// Natural resources decision: Retain the existing `naturalresources` topic as canonical. Its stable ID is already stored in iOS user preferences and used by natural-resource context features, so the backend must adopt that same ID and keyword set instead of dropping it.
var topics = []topic{
	{id: "housing", name: "Housing", keywords: []string{"housing", "rent", "mortgage", "affordable housing", "logement", "loyer"}},
	{id: "healthcare", name: "Healthcare", keywords: []string{"health", "pharmacare", "mental health", "dental", "pandemic", "santé"}},
	{id: "climate", name: "Climate", keywords: []string{"climate", "carbon", "environment", "clean energy", "net zero", "emission", "énergie", "environnement"}},
	{id: "economy", name: "Economy", keywords: []string{"budget", "fiscal", "inflation", "economic", "gdp", "debt", "déficit", "économie"}},
	{id: "indigenous", name: "Indigenous affairs", keywords: []string{"indigenous", "first nations", "métis", "inuit", "reconciliation", "autochtone"}},
	{id: "immigration", name: "Immigration", keywords: []string{"immigration", "refugee", "asylum", "citizenship", "border", "réfugié"}},
	{id: "defence", name: "Defence", keywords: []string{"defence", "military", "NATO", "armed forces", "veteran", "Veterans Affairs", "ancien combattant", "défense", "armée"}},
	{id: "justice", name: "Justice & Public Safety", keywords: []string{"justice", "crime", "police", "firearms", "gun", "corrections", "correctional", "prison", "parole", "recidivism", "incarceration", "sécurité"}},
	{id: "seniors", name: "Seniors", keywords: []string{"senior", "pension", "retirement", "old age", "aîné", "retraite"}},
	{id: "agriculture", name: "Agriculture", keywords: []string{"agriculture", "farming", "food security", "grain", "livestock"}},
	{id: "transport", name: "Transport & Infrastructure", keywords: []string{"transport", "rail", "aviation", "highway", "infrastructure", "transit"}},
	{id: "taxation", name: "Taxation", keywords: []string{"tax", "GST", "HST", "income tax", "corporate tax", "impôt", "taxe"}},
	{id: "foreign", name: "Foreign Affairs", keywords: []string{"foreign affairs", "international", "Ukraine", "Gaza", "sanctions", "treaty", "affaires étrangères"}},
	{id: "education", name: "Education", keywords: []string{"education", "student", "student debt", "youth", "university", "school", "tuition", "éducation", "étudiant"}},
	{id: "childcare", name: "Child Care", keywords: []string{"child care", "daycare", "family", "children", "services de garde", "enfant"}},
	{id: "energy", name: "Energy", keywords: []string{"energy", "oil", "gas", "pipeline", "electricity", "LNG", "pétrole"}},
	{id: "naturalresources", name: "Natural Resources", keywords: []string{"natural resources", "forestry", "forest", "lumber", "timber", "mining", "minerals", "mineral production", "potash", "wood harvest", "ressources naturelles", "foresterie", "mines"}},
	{id: "pharma", name: "Pharmaceuticals", keywords: []string{"drug", "pharmaceutical", "medication", "opioid", "naloxone", "médicament"}},
	{id: "digital", name: "Digital & AI", keywords: []string{"digital", "artificial intelligence", "AI", "online harms", "privacy", "cybersecurity", "numérique"}},
	{id: "labour", name: "Labour", keywords: []string{"labour", "labor", "union", "strike", "wage", "employment", "travail", "grève"}},
	{id: "trade", name: "Trade", keywords: []string{"trade", "tariff", "CUSMA", "CETA", "export", "import", "commerce", "tarif"}},
}

// matchTopics returns IDs of topics whose keywords appear in the subject title.
func matchTopics(subjectTitle string) []string {
	lower := strings.ToLower(subjectTitle)
	var matched []string
	for _, t := range topics {
		for _, kw := range t.keywords {
			if strings.Contains(lower, strings.ToLower(kw)) {
				matched = append(matched, t.id)
				break
			}
		}
	}
	return matched
}

func topicName(id string) string {
	for _, t := range topics {
		if t.id == id {
			return t.name
		}
	}
	return id
}
